### ISSUE TITLE
Returned values aren't valid, did it run Out of Gas

### ISSUE THREAD

**Issue by adel1ne** [compound-developers/compound-supply-examples#11]
**Problem**
```
ganache-cli \
  -f https://mainnet.infura.io/v3/<MyProjectId> \
  -m "clutch captain shoe salt awake harvest setup primary inmate ugly among become" \
  -i 1 \
  -u 0x9759A6Ac90977b93B58547b4A71c78317f391A28
```

`node web3-js-examples/supply-eth-via-web3.js`

**Got Error:**

```
My wallet's ETH balance: 98.99957872

Supplying ETH to the Compound Protocol...

cETH "Mint" operation successful.

Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, o
r querying a node which is not fully synced.
    at ABICoder.decodeParameters (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\web3-eth-abi\lib\index.js:288:15)
    at Contract._decodeMethodReturn (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\web3-eth-contract\lib\index.js:470:22)
    at Method.outputFormatter (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\web3-eth-contract\lib\index.js:760:42)
    at Method.formatOutput (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\web3-core-method\lib\index.js:147:54)
    at sendTxCallback (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\web3-core-method\lib\index.js:523:33)
    at C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\web3-core-requestmanager\lib\index.js:293:9
    at XMLHttpRequest.request.onreadystatechange (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\web3-providers-http\lib\index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\xhr2-cookies\dist\xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (C:\Users\adel1\PhpstormProjects\compound-supply-examples\node_modules\xhr2-cookies\dist\xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Seems to be method **cEthContract.methods.mint().send()** executing correctly and balance of ETH wallet is changing. But after that all other methods returning same error (see above).

**Comment by adel1ne** [comment]
Sorry, my mistake, i ran `ganacha-cli` without params, cause windows cmd didn't recognize '\' and in this command:
```
ganache-cli \
  -f https://mainnet.infura.io/v3/<MyProjectId> \
  -m "clutch captain shoe salt awake harvest setup primary inmate ugly among become" \
  -i 1 \
  -u 0x9759A6Ac90977b93B58547b4A71c78317f391A28
```
executed only ganache-cli :)
