### ISSUE TITLE
project ID does not have access to archive state

### ISSUE THREAD

**Issue by TimothyDalbey** [compound-developers/compound-supply-examples#2]
Using the Ganache CLI as below:
```timothydalbey@MacBook-Pro-5 compound-borrow % ./node_modules/.bin/ganache-cli \
  -f https://mainnet.infura.io/v3/{project_id} \
  -m "clutch captain shoe salt awake harvest setup primary inmate ugly among become" \
  -i 999 \
  -u 0x9759A6Ac90977b93B58547b4A71c78317f391A28
```

After executing the following successfully: `node mint-testnet-dai.js`

The supply script `supply-erc20-via-web3.js` throws the following error:  
```timothydalbey@MacBook-Pro-5 web3-js-examples % node supply-erc20-via-web3.js
Error: Returned error: Returned error: project ID does not have access to archive state
    at Object.ErrorResponse (/Users/timothydalbey/Development/crypto/experimental/supply/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/timothydalbey/Development/crypto/experimental/supply/node_modules/web3-core-requestmanager/src/index.js:166:36
    at XMLHttpRequest.request.onreadystatechange (/Users/timothydalbey/Development/crypto/experimental/supply/node_modules/web3-providers-http/src/index.js:110:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/timothydalbey/Development/crypto/experimental/supply/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/timothydalbey/Development/crypto/experimental/supply/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/timothydalbey/Development/crypto/experimental/supply/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/timothydalbey/Development/crypto/experimental/supply/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by ajb413** [comment]
Try restarting your ganache-cli of the forked chain. If you leave it running for too long this issue may come up.

If that doesn't work, and you're using Cloudflare as an HTTP provider, try using a different HTTP provider, like Infura.io.
