### ISSUE TITLE
'Out of gas' - Local Network with Ganache - Proposed Fix

### ISSUE THREAD

**Issue by CT83** [compound-developers/compound-supply-examples#4]
### Problem

```
ganache-cli  -f https://cloudflare-eth.com/  -m "clutch captain shoe salt awake harvest setup primary inmate
ugly among become" -i 999 -u 0x9759A6Ac90977b93B58547b4A71c78317f391A28
```

`$ node supply-eth-via-web3.js`

```
Each supplied ETH will increase by 1.04293981e-9 this block, based on the current interest rate.
Supplying ETH to the Compound Protocol...
cETH "Mint" operation successful.
ETH supplied to the Compound Protocol: 0.999999999997789607
My wallet's cETH Token Balance: 49.96884526
Current exchange rate from cETH to ETH: 0.020012469665739673
Redeeming the cETH for ETH...
Exchanging all cETH based on cToken amount...
Error: Returned error: Exceeds block gas limit
    at Object.ErrorResponse (D:\Code\NodeJS\compound-supply-examples\node_modules\web3-core-helpers\src\errors.js:29:16)
    at D:\Code\NodeJS\compound-supply-examples\node_modules\web3-core-requestmanager\src\index.js:170:36
    at XMLHttpRequest.request.onreadystatechange (D:\Code\NodeJS\compound-supply-examples\node_modules\web3-providers-http\src\index.js:111:13)
    at XMLHttpRequestEventTarget.dispatchEvent (D:\Code\NodeJS\compound-supply-examples\node_modules\xhr2-cookies\dist\xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (D:\Code\NodeJS\compound-supply-examples\node_modules\xhr2-cookies\dist\xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (D:\Code\NodeJS\compound-supply-examples\node_modules\xhr2-cookies\dist\xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (D:\Code\NodeJS\compound-supply-examples\node_modules\xhr2-cookies\dist\xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

### Proposed Fix

Here is how I fixed it. I am new to Blockchain, so I am not totally sure this is the right way to fix things.

```
ganache-cli  -f https://cloudflare-eth.com/  -m "clutch captain shoe salt awake harvest setup primary inmate
ugly among become" -i 999 -u 0x9759A6Ac90977b93B58547b4A71c78317f391A28 -l 15000000000
```

web3-js-examples\supply-eth-via-web3.js
`line 54 - gasLimit: web3.utils.toHex(1500000000),  `

**Comment by DanielTongAwesome** [comment]
increase the gas limit
